### ISSUE TITLE
Contribute to Reactor

### ISSUE THREAD

**Issue by sirinath** [ifesdjeen/halflife#2]
I am wondering if this can be contributed to reactor?

**Comment by ifesdjeen** [comment]
cc @smaldini :) Can this be contributed to reactor? :)

**Comment by smaldini** [comment]
Feel free to PR a new module under reactor/reactor. It will help me in reviewing the changes for 2.1 since Dispatcher (don't worry there's an iso feature replacement in line with RS) and Environment go away and reactor-core is loosing weight.

**Comment by sirinath** [comment]
Looking forward to this being in reactor!

**Comment by ifesdjeen** [comment]
So, working on integration!
